////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= Guidelines

Logging Services is a _project_ of the https://apache.org[Apache Software Foundation] (ASF) and composed of several _subprojects_; Log4cxx, Log4j, Log4Net, etc.
Logging Services _Project Management Committee (PMC)_ is responsible for the management of the project and all its subprojects.
Committers and PMC members are elected due to merit for the evolution of the project.
Changes and releases are subject to voting.
All ASF projects are operated using this governance model, which is further documented in the following pages:

* https://apache.org/foundation/how-it-works[How the ASF works]
* http://www.apache.org/foundation/faq.html[The ASF FAQ]
