////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= {project-name}

The Apache Logging Services project creates and maintains open-source software related to the logging of application behavior and released at no charge to the public.

[#shortcuts]
== Shortcuts

* xref:what-is-logging.adoc[]
* xref:support.adoc[Get **support** for subprojects]
* xref:download.adoc[**Download** subprojects]
* xref:security.adoc[Vulnerabilities and threat model]

[#subprojects]
== Subprojects

https://logging.apache.org/log4j[Log4j®]::
A versatile, industrial-grade Java logging framework composed of an API, its implementation, and components to assist the deployment for various use cases.
+
https://logging.apache.org/log4j/kotlin[Log4j® Kotlin]:::
A Kotlin-friendly interface to log against the Log4j® API.
+
https://logging.apache.org/log4j/kotlin[Log4j® Scala]:::
A Scala-friendly interface to log against the Log4j® API.

https://logging.apache.org/log4cxx[Log4cxx]::
A logging framework for C++ patterned after Log4j®.

https://logging.apache.org/log4Net[Log4Net]::
A port of the Log4j® to the Microsoft .NET runtime.

.Click to see list of dormant subprojects
[%collapsible]
====
https://logging.apache.org/chainsaw[Chainsaw]::
A GUI-based log viewer intended as a companion to Log4j®.

https://logging.apache.org/flume[Flume]::
Distributed, reliable, and available service for efficiently collecting, aggregating, and moving large amounts of log data.

https://logging.apache.org/log4j/1.x[Log4j® 1]::
The very first Log4j® major release.
Reached End-Of-Life in August 2015.

https://logging.apache.org/log4j-audit/latest[Log4j® Audit]::
Audit logging framework built upon Apache Log4j®.

https://logging.apache.org/log4j/extras[Log4j® Extras]::
Extras for Log4j® 1; companions, receivers, and more.

https://logging.apache.org/log4php[Log4php]::
A versatile logging framework for PHP.
Originally a port of Log4j® to PHP, it has grown to include various PHP specific features.
====
