notifications:
  commits:      commits@logging.apache.org
  issues:       notifications@logging.apache.org
  pullrequests: notifications@logging.apache.org
  jira_options: link label comment

staging:
  whoami: asf-staging
  profile: ~

publish:
  whoami: asf-site

# Dummy value to trigger CI
