publish:
  whoami: main-site-pro-out
  subdir: content


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 10681
# - Commit ID: c3de0700b34b80ead6bae76ca6442c53a3a0fb4a
# - Timestamp: 2026-06-25T20:17:14Z
