notifications:
  commits:      commits@logging.apache.org
  issues:       notifications@logging.apache.org
  pullrequests: notifications@logging.apache.org
  jira_options: link label comment 

#staging:
#  profile: ~
#  whoami: asf-staging
#
#publish:
#  profile: ~
#  whoami: asf-site

jekyll:
  whoami: jekyll
  target: asf-staging
staging:
  whoami: asf-staging
publish:
  whoami: asf-site
