publish:
  whoami: main-site-pro-out
  subdir: content


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 8483
# - Commit ID: 15505b509ba025e2a4a443bf5cd791f319a48224
# - Timestamp: 2026-10-06T20:00:23Z
