notifications:
  commits:      commits@logging.apache.org
  issues:       notifications@logging.apache.org
  pullrequests: notifications@logging.apache.org
  jira_options: link label comment 

jekyll:
  whoami: jekyll
  target: asf-staging
  outputdir: content
staging:
  profile: ~
  whoami: asf-staging
publish:
  whoami: asf-site
