staging:
  profile: ~
  whoami: main-site-stg-out

# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 5480
# - Commit ID: bcbe66cae1e7b5a2d857bce3c161d0400901f991
# - Timestamp: 2025-12-31T11:21:07Z
