staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 12336
# - Commit ID: 2c590909eec2ec5fa26cb31b2d32b2bfd4459b97
# - Timestamp: 2026-08-18T13:17:43Z
