notifications:
  commits:      commits@logging.apache.org
  issues:       notifications@logging.apache.org
  pullrequests: notifications@logging.apache.org
  jira_options: link label comment 

jekyll:
  profile: ~
  whoami: jekyll
  outputdir: content
  target: asf-staging
