////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= Download

You can use one of the following channels to download the Logging Services release distributions.

[IMPORTANT]
====
All Logging Services projects distribute convenience binaries that are easy to install for the programming language platform they target.
You are strongly advised to **check the installation instructions in the website of the project** (link:/log4cxx[Log4cxx], link:/log4j[Log4j], link:/log4net[Log4net], etc.) you are trying to install.
====

Official distribution channels::
In accordance with the Apache Software Foundation's release https://infra.apache.org/release-distribution.html[distribution policy] and https://infra.apache.org/release-publishing.html[creation process], all Logging Services release distributions are _officially_ accessible from the following channels:
* ASF https://downloads.apache.org/logging[Distribution directory] (contains **the most recent releases**)
* ASF https://archive.apache.org/dist/logging[Distribution directory **archive**] (contains all published releases)

Java distribution channels::
* ASF https://repository.apache.org/content/repositories/releases[Release] and https://repository.apache.org/content/repositories/snapshots[snapshot] Nexus repositories (mirrored to https://central.sonatype.dev/[the Maven Central Repository])

.NET distribution channels::
* https://www.nuget.org/profiles/asf[`asf` organization in NuGet]

[#verify]
== Verification

All Logging Services release distributions are digitally signed by the release manager and provided with checksum files.
You can verify a distribution by following the below shared instructions:

[source,bash]
----
# Download and import the release manager public keys
wget -O - https://downloads.apache.org/logging/KEYS | gpg --import

# Verify signatures
for sigFile in *.asc; do gpg --verify $sigFile; done

# Verify checksums
shasum --check *.sha512
----

[#sbom]
== Software Bill of Materials (SBOM)

include::_sbom.adoc[]
