////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= Log4j participates in the bug bounty program

We were proud to be xref:blog/20231214-announcing-support-from-the-stf.adoc[supported by the STF] last year.
This support helped us to fix many bugs, rewrite documentation, and improve the overall quality of the codebase and security.

Building on this support, we are excited to announce our participation in the https://yeswehack.com/programs/log4j-bug-bounty-program[YesWeHack] bug bounty program.
This initiative allows you to hunt bugs in Log4j and get paid for your contributions.

Our participation in this program wouldn't have been possible without the 
generous support of our friends at the STF, who provided the necessary funds to 
reward your efforts. The STF not only supports us but also assists many other projects. 
You can learn more about their mission by reading their
https://www.sovereigntechfund.de/news/calling-all-security-researchers[official announcement on their website].

We want to thank the STF and YesWeHack for their support.

We encourage all security researchers and developers to join us in this effort. 
Your contributions can help make Log4j more secure and reliable and reward your efforts.
