////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= Apache Log4j at Community Over Code 2024 in Bratislava

On July 25, 2024, Apache Log4j was featured at the Community Over Code conference in Bratislava.
Matt Sicker and Piotr Karwasz, two of the project's key contributors, shared insights into the history and future of Log4j.

If you are interested in what we learned about security and how we want to 
improve Log4j further, please watch https://www.youtube.com/watch?v=Hpe7p24DQo0[the full interview done by Rich Bowen for the ASF].
