////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= XML Schemas for Apache Logging Services projects

All XML Schemas for Apache Logging Services projects are published at this directory.
The canonical name for this directory is `https://logging.apache.org/xml/ns`.

[IMPORTANT]
====
There are two important things to understand about XSD versioning scheme used here to employ these schemas in your applications:

. *Schema versions and project versions evolve independently.*
That is, Log4j `2.24.0` release does not necessarily mean a new `log4j-config-2.24.0.xsd`: the Log4j 2 runtime configuration API might have been kept intact.
. *Users are recommended to use schemas with only major versions*; `log4j-config-2.xsd`, `log4j-config-3.xsd`, `log4j-changelog-0.xsd`, etc.
====

[#log4j]
== Log4j schemas

xref:/log4j[Log4j] is a Java logging framework.
Following schemas model the Log4j runtime configuration, i.e., `log4j2.xml`{empty}footnote:[Both Log4j 2 and Log4j 3 use `log4j2.xml` for configuration.].

[%header,cols="3*"]
|===
|Publication date
|File name
|Description

|2024-03-19
|xref:log4j-config-2.23.1.xsd[]
|Released with link:/log4j/2.x/release-notes.html#release-notes-2-23-1[Log4j `2.23.1`]

|N/A
|xref:log4j-config-2.xsd[]
|Points to the most recent XSD of major version `2`.
*Log4j 2 users are recommended to refer to this XSD in their XML files.*

|2024-03-19
|xref:log4j-config-3.0.0.xsd[]
|N/A

|N/A
|xref:log4j-config-3.xsd[]
|Points to the most recent XSD of major version `3`.
*Log4j 3 users are recommended to refer to this XSD in their XML files.*
|===

.Example Log4j 2 schema usage
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<Configuration xmlns="https://logging.apache.org/xml/ns"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://logging.apache.org/xml/ns https://logging.apache.org/xml/ns/log4j-config-2.xsd">
  <Appenders>
    <Console name="Console" target="SYSTEM_OUT">
      <PatternLayout pattern="%d [%t] %p %c - %m%n"/>
    </Console>
  </Appenders>
  <Loggers>
    <Root level="WARN">
      <AppenderRef ref="Console"/>
    </Root>
  </Loggers>
</Configuration>
----

[#log4j-changelog]
== Log4j Changelog schemas

link:/log4j/tools/latest/#log4j-changelog[Log4j Changelog] is a tool to maintain changelogs.
It is designed for Apache Log4j, but can be used for any Java project.

[%header,cols="3*"]
|===
|Publication date
|File name
|Description

|2023-02-03
|xref:log4j-changelog-0.1.0.xsd[]
|Released with link:/log4j/tools/latest/#release-notes-0-2-0[Log4j Tools `0.2.0`]

|2023-03-17
|xref:log4j-changelog-0.1.1.xsd[]
|Released with link:/log4j/tools/latest/#release-notes-0-3-0[Log4j Tools `0.3.0`]

|2023-09-28
|xref:log4j-changelog-0.1.2.xsd[]
|Released with link:/log4j/tools/latest/#release-notes-0-5-0[Log4j Tools `0.5.0`]

|2023-12-13
|xref:log4j-changelog-0.1.3.xsd[]
|Released with link:/log4j/tools/latest/#release-notes-0-7-0[Log4j Tools `0.7.0`]

|2024-03-15
|xref:log4j-changelog-0.2.0.xsd[]
|Planned to be released with Log4j Tools `0.8.0`

|N/A
|xref:log4j-changelog-0.xsd[]
|Points to the most recent XSD of major version `0`.
*Users are recommended to refer to this XSD in their XML files.*
|===

.Example Log4j Changelog schema usage
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<entry xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="https://logging.apache.org/xml/ns"
       xsi:schemaLocation="
               https://logging.apache.org/xml/ns
               https://logging.apache.org/xml/ns/log4j-changelog-0.xsd"
       type="updated">
  <issue id="2370" link="https://github.com/apache/logging-log4j2/pull/2370"/>
  <description format="asciidoc">Update `actions/checkout` to version `4.1.2`</description>
</entry>
----
