////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= XML Schemas for Apache Logging Services projects

All XML Schemas for Apache Logging Services projects are published at this directory.
The canonical name for this directory is `https://logging.apache.org/xml/ns`.

[#log4j-changelog]
== `log4j-changelog` schemas

https://logging.apache.org/log4j/tools/latest/#log4j-changelog[log4j-changelog] is a tool to maintain changelogs.
It is designed for Apache Log4j, but can be used for any Java project.

[%header,cols="3*"]
|===
|Publication date
|File name
|Associated release

|2023-02-03
|xref:log4j-changelog-0.1.0.xsd[]
|xref:/log4j/tools/latest/#release-notes-0-2-0[Log4j Tools `0.2.0`]

|2023-03-17
|xref:log4j-changelog-0.1.1.xsd[]
|xref:/log4j/tools/latest/#release-notes-0-3-0[Log4j Tools `0.3.0`]

|2023-09-28
|xref:log4j-changelog-0.1.2.xsd[]
|xref:/log4j/tools/latest/#release-notes-0-5-0[Log4j Tools `0.5.0`]

|2023-12-13
|xref:log4j-changelog-0.1.3.xsd[]
|xref:/log4j/tools/latest/#release-notes-0-7-0[Log4j Tools `0.7.0`]

|2024-??-??
|xref:log4j-changelog-0.2.0.xsd[]
|N/A
|===
